# -*- coding: utf-8 -*-
"""Prod_Price_tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mtkssDH9Brk1AmiRgIni_0e8bW_qkhCy
"""

import requests
from bs4 import BeautifulSoup
import smtplib
import time

headers = {
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
}

# Request to fetch html of the page
response = requests.get('https://www.amazon.in/Bose-Noise-Cancelling-Headphones-Black/dp/B07Q9MJKBV/ref=sr_1_2?pf_rd_i=1388921031&pf_rd_m=A1K21FY43GMZF8&pf_rd_p=c1c12ca6-cdff-4b9e-a644-85314e7d32dd&pf_rd_r=V2NC2QWC40HWV92P3MVF&pf_rd_s=merchandised-search-19&pf_rd_t=101&qid=1657435204&refinements=p_85%3A10440599031%2Cp_89%3ABose&rps=1&s=electronics&sr=1-2', headers=headers)

soup = BeautifulSoup(response.content, 'html.parser')
soup.encode('utf-8')
print(soup.prettify())

def check_price():
  title = soup.find(id= "productTitle").get_text()
  price = soup.find(id = "priceblock_ourprice").get_text().replace(',', '').replace('₹', '').replace(' ', '').strip()
  print(price)
  converted_price = float(price[0:5])
  print(converted_price)
  if(converted_price < 25000):
    send_mail()
  print(title.strip())

def send_mail():
  server = smtplib.SMTP('smtp.gmail.com', 587)
  server.ehlo()
  server.starttls()
  server.ehlo()

  server.login('email@gmail.com', 'password')

  subject = 'Price Fell Down'
  body = "Check the amazon link https://www.amazon.in/Bose-Noise-Cancelling-Headphones-Black/dp/B07Q9MJKBV/ref=sr_1_2?pf_rd_i=1388921031&pf_rd_m=A1K21FY43GMZF8&pf_rd_p=c1c12ca6-cdff-4b9e-a644-85314e7d32dd&pf_rd_r=V2NC2QWC40HWV92P3MVF&pf_rd_s=merchandised-search-19&pf_rd_t=101&qid=1657435204&refinements=p_85%3A10440599031%2Cp_89%3ABose&rps=1&s=electronics&sr=1-2 "

  msg = f"Subject: {subject}\n\n{body}"
  
  server.sendmail(
    'sender@gmail.com',
    'receiver@gmail.com',
    msg
  )

print('Hey Email has been sent')

server.quit()

while(True):
  check_price()
  time.sleep(60 * 60)